@include('includes.head')
@if(Auth::user())
    @include('includes.auth-menus')
@else
    @include('includes.menus')
@endif
@if(!Auth::user())
    @include('includes.slider')
@endif
@yield('content')
@include('includes.footer')